Init workflow
oicr-gsi/sniffles pull request #1
Opened 2019-10-09 19:08 UTC by matthewwong525

2019-10-10 15:40 UTC, matthewwong525 commented
retest this please

2019-10-10 20:42 UTC, matthewwong525 commented
retest this please

2019-10-10 20:43 UTC, matthewwong525 commented
retest this please

2019-11-20 17:34 UTC, mlaszloffy requested changes

2019-11-20 17:34 UTC, mlaszloffy commented on sniffles.wdl
> +        sortedBamFile: "Input directory (directory of the nanopore run)"
Can the description be updated to "Input bam file (must be sorted)"

2019-11-20 17:34 UTC, mlaszloffy commented on sniffles.wdl
> +        String outputFileNamePrefix
Maybe a default of `basename(sortedBamFile, ".bam")`

2019-11-22 20:50 UTC, matthewwong525 commented
retest this please

2019-12-06 14:04 UTC, mlaszloffy approved these changes

2019-12-06 14:14 UTC, lheisler commented on sniffles.wdl
> +        email: "m2wong@oicr.on.ca"
this email address will disappear once you leave OICR.  absolutely fine to include your name, but i don't think it makes sense to use this address.

2019-12-06 14:15 UTC, lheisler commented on sniffles.wdl
> +        description: "Workflow to run Structural Variant caller"
description can be more specific, "Workflow to run the Structural Variant caller Sniffles on Oxford Nanopore Data"

2019-12-06 14:16 UTC, lheisler approved these changes

2019-12-13 17:32 UTC, merged